spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/lora_3rd_part
    username: umka
    password: umka
    server-url: localhost:4200
    #url: jdbc:postgresql://postgres:5432/business_center
    #username: lora_user
    #password: lora_user
    #server-url: 185.160.63.20
    driverClassName: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      pool-name: lora-app-pool

  jpa:
    database: postgresql

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

  main:
    web-environment: true

server:
  port: 8989

last-packets:
  synchronize-time: 60000
